# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-21 12:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('AccountId', models.BigAutoField(primary_key=True, serialize=False)),
                ('AccountNo', models.CharField(max_length=350, unique=True)),
                ('AccountHoldersName', models.CharField(max_length=350)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Sex', models.CharField(max_length=100)),
                ('ContactNo', models.BigIntegerField()),
                ('ContactEmail', models.CharField(max_length=300)),
                ('createdOn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('AccountTypeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('AccountTypeName', models.CharField(max_length=350, unique=True)),
                ('AccountTypeShortName', models.CharField(max_length=350, unique=True)),
                ('createdOn', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('LoginName', models.CharField(max_length=100)),
                ('vchr_UserName', models.CharField(max_length=150, unique=True)),
                ('vchr_email', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='accounttype',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.UserDetails'),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='AccountTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.AccountType'),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_details.UserDetails'),
        ),
    ]
